### PR TITLE
Added link to county codes

### PR DESCRIPTION
**Pull request by boredstiff**
Added link to county codes

### CODE REVIEW

**Comment by mkearney** [comment]
merge

**Comment by boredstiff** [comment]
I'm sorry, I don't understand - I'm asking to merge, as it might be helpful for people to look up or correlate their county code (as I did). 

Are you choosing not to merge? If not, totally fine, just clarifying what you wanted. Thanks for putting these up!

**Comment by mkearney** [comment]
Idk what I did. Tried to accept on mobile. I can add a col of county names later tonight or tomorrow.

**Comment by mkearney** [comment]
I figured it out I think lol. Thanks!

**Pull request merged**
